server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: admin
    password: admin
    driverClassName: org.h2.Driver